### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by huyaxiong** [andruschka/pm2-meteor#13]
reaction-8 Error: Module did not self-register.
reaction-8     at Error (native)
reaction-8     at Module.load (module.js:355:32)
reaction-8     at Function.Module._load (module.js:310:12)
reaction-8     at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
reaction-8     at Module.require (module.js:365:17)
reaction-8     at require (module.js:384:17)
reaction-8     at Object.Npm.require (/node/reaction.ffshtest.net/reaction/bundle/programs/server/boot.js:162:18)
reaction-8     at packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:10:1
reaction-8     at packages/npm-node-aes-gcm/packages/npm-node-aes-gcm.js:25:1
reaction-8     at /node/reaction.ffshtest.net/reaction/bundle/programs/server/packages/npm-node-aes-gcm.js:45:4

pm2-meteor v0.3.2
node v4.2.2
pm 2.14.7

Can you help me solve it?

**Comment by huyaxiong** [comment]
Here's the test project https://github.com/reactioncommerce/reaction.git

**Comment by andruschka** [comment]
Would be very useful if you could add your pm2-meteor.json file 🤔

**Comment by trinisofttechnologies** [comment]
@huyaxiong That is because you are using a higher version of nodejs, 
you need to use either 0.10.36 or as per the latest one 0.10.40

Thanks

**Comment by huyaxiong** [comment]
OK,Thank you!
