### ISSUE TITLE
About settings/production.json

### ISSUE THREAD

**Issue by katopz** [andruschka/pm2-meteor#14]
refer to

```
"meteorSettingsLocation": "settings/production.json"
```

I can't find anything related to `production.json` What to be expect content there?

**Comment by katopz** [comment]
Like usual, to answer my own question https://themeteorchef.com/snippets/making-use-of-settings-json/

**Comment by andruschka** [comment]
Sorry very busy this month - You just wanted to know what the meteor settings file is or what this property do? in meteorSettingsLocation you can define the path to your meteor settings file - this will be then transormed to a METEOR_SETTINGS env variable in the pm2-env.json which will start your application on the server
