### ISSUE TITLE
Getting cluster worker id?

### ISSUE THREAD

**Issue by dnish** [andruschka/pm2-meteor#17]
Hey,
if I'm scaling my app and start multiple instances, is it possible to get a unique id for each child proccess? For example, on Meteor Cluster we have:

```
process.env.CLUSTER_WORKER_ID
```

I would need it for our cronjobs. A cronjob should only be executed on worker "1".

**Comment by mwkrieger** [comment]
I'm looking for this, too. Any way to do this?

**Comment by andruschka** [comment]
You mean like predefining ids for PM2 ?

**Comment by andruschka** [comment]
yes I finally found it 😆 

> process.env.pm_id

**Comment by dnish** [comment]
Mh okay, we are using

```
process.env.NODE_APP_INSTANCE 
```

with success. I don't know if there are any differences between these two?

Nice to have for cronjob that clean up the database and should only run on a single instance :)

**Comment by andruschka** [comment]
I am currently not sure what node_app_instance is for - but I tested it 5 min ago and if you are using the clustering system from pm2 ( like pm2 scale +2 ) then you should use :

> process.env.pm_id

**Comment by dnish** [comment]
Ah okay, I think the issue is discussed here:

https://github.com/Unitech/PM2/issues/1143

Have to say that I couldn't read out the main difference between these two?

**Comment by andruschka** [comment]
Hmm I just ran a script like `pm2 start test.js -i 4` and then `pm2 list` then they have different ids.
And the script does 

```
console.log(process.env.NODE_APP_INSTANCE)
console.log(process.env.pm_id)
```

the result always looks like:
0

## 0

0

## 1

0

## 2

...and so on.
So the process.env.NODE_APP_INSTANCE always returns 0 on my machine ?!?!

**Comment by dnish** [comment]
Uff...if I remember right, somebody has posted that <code>process.env.NODE_APP_INSTANCE</code> only works in cluster mode?

**//Edit**

Didn't read the -i parameter. In my case, everything works fine:

```
0|test     | 0
1|test     | 1
2|test     | 2
3|test     | 3
```

```
console.log(process.env.NODE_APP_INSTANCE);
```

Command:

```
pm2 start test.js -i 4
```

**Comment by andruschka** [comment]
😮  thats the exact same thing ive done - but in my case NODE_APP_INSTANCE always was 0 ...
crazy

**Comment by dnish** [comment]
@andruschka After some debugging I find out that we have the same issue in our Meteor app. I'm starting 4 instances:

    0|meteor-app -> 0
    1|meteor-app -> 1
    3|meteor-app -> 0
    4|meteor-app -> 0

Strange...
