### ISSUE TITLE
QUESTION: Is this running on WINDOWS SERVER 2012

### ISSUE THREAD

**Issue by faavictoriano** [andruschka/pm2-meteor#24]
Sir i would like to as if the pm2-meteor is running or tested on windows server?
Any guide to deploy?

**Comment by andruschka** [comment]
No sorry i absolutely dont know if this will run on windows - we are using freebsd and ubuntu only 😢  sorry- but would be nice if you could test it - and if you have the time - and it isnt working maybe a commit ?
