### ISSUE TITLE
Meteor warning in PM2 error logs

### ISSUE THREAD

**Issue by dnish** [andruschka/pm2-meteor#25]
While the deployment issue with bcrypt seems to be fixed, I get the following warning in my PM2 logs after deploying the new app (Meteor 1.4.1):

```
-web-0 (err): 
-web-0 (err):   meteor npm install --save bcrypt
-web-0 (err): 
-web-0 (err): in the root directory of your application.
-web-0 (err): Note: you are using a pure-JavaScript implementation of bcrypt.
-web-0 (err): While this implementation will work correctly, it is known to be
-web-0 (err): approximately three times slower than the native implementation.
-web-0 (err): In order to use the native implementation instead, run
-web-0 (err): 
-web-0 (err):   meteor npm install --save bcrypt

```

I already run the command on my development version, it seems like we need to run it again in production. Any idea if we could add a hook into pm2-meteor that executes it after unzipping?

**Comment by andruschka** [comment]
Yes I will have a look - but if you want to contribute - commits welcome

**Comment by zhanbst** [comment]
node-gyp rebuild on npm/bcrypt

**Comment by andruschka** [comment]
this is actually a meteor / bcrypt madness...
I think this happens when you install bcrypt with another version of node.
Just do:
`npm remove bcrypt --save`
`rm -rf node_modules`
`meteor npm install bcrypt --save`
`meteor npm install`
