### ISSUE TITLE
Please make sure you have node, npm and pm2 installed on your remote machine!

### ISSUE THREAD

**Issue by crapthings** [andruschka/pm2-meteor#27]
i do have node npm pm2 installed, why i've still got this ?

node v4.5.0
npm v2.15.9

tried npm i -g pm2 and npm i -g pm2@next

**Comment by crapthings** [comment]
Building your app and deploying to host machine -
missing pm2

**Comment by andruschka** [comment]
hmm do you have multiple versions of node installed ?

**Comment by andruschka** [comment]
or are you using nvm maybe

**Comment by crapthings** [comment]
yes i do have nvm installed

**Comment by crapthings** [comment]
i've install a fresh new ubuntu 14.04 lts on vmware.

and do a clean environment installation and works.

i will try if i have nvm on server

thanks

**Comment by andruschka** [comment]
If you later want to use with nvm you should fill in the nvm: {}  Object in the pm-meteor.json file. It has a bin: "" and a use: "" property -> The error you got was because when pm2meteor opened a connection to you machine - the wrong node version was loaded up - the which doesnt have pm2 installed ^^

**Comment by ilan-schemoul** [comment]
> There is a naming conflict with the node package (Amateur Packet Radio Node Program), and the nodejs binary has been renamed from node to nodejs. You'll need to symlink /usr/bin/node to /usr/bin/nodejs or you could uninstall the Amateur Packet Radio Node Program to avoid that conflict.

why don't you use Nodejs name instead of Node if Node has been renamed ?
