### ISSUE TITLE
Please guide me about mongoDB install

### ISSUE THREAD

**Issue by cyclops24** [andruschka/pm2-meteor#34]
Hi @andruschka first thanks for this awesome tools but I think [tutorial](http://pm2-meteor.betawerk.co/) needs more detail for example in "Step three (prepare mongodb) - on host":
I try install mongoDB based on this like below:
`apt-get install mongodb-server` but it's install mongoDB version 2.6.10 until Meteor 1.4.x use MongoDB version 3.x?
How we can install 3.x mongo?

**Comment by andruschka** [comment]
Ah yes I had this problem also the first time... If you want the latest mongoDB you need to follow these steps : 
```
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

$ echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

$ sudo apt-get update

$ sudo apt-get install -y mongodb-org
```
This is for Ubuntu 14.x.
See [official mongo site](https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-ubuntu/) for more infos...
I hope this helps you .
