### ISSUE TITLE
ERROR: Please make sure you have node, npm and pm2 installed on your remote machine!

### ISSUE THREAD

**Issue by cyclops24** [andruschka/pm2-meteor#37]
Hi @andruschka  I follow [tutorial](http://pm2-meteor.betawerk.co/) step by step but when I run `pm2-meteor deploy` it returns below error:
```
Building your app and deploying to host machine -
missing node


ERROR: Please make sure you have node, npm and pm2 installed on your remote machine!
```

I also see [this closed issue](https://github.com/andruschka/pm2-meteor/issues/27) but I haven't any NVM in my host or local.
This is some output from my host:
```
nodejs --version
v4.2.6
npm --version
3.5.2
```

**Comment by cyclops24** [comment]
Oh It seems its about PM2.
When I run `pm2 -v` on my host it returns below otuput:
```
pm2 -v
/usr/bin/env: 'node': No such file or directory
```
I see [this issue](https://github.com/Unitech/pm2/issues/455) and based on that run following command on my host:
```
ln -s /usr/bin/nodejs /usr/bin/node
```
it seems to be because `apt-get` installs the node binary as 'nodejs' and pm2 is looking for 'node'.
Now when I run `pm2 -v` it's return below output:
```
pm2 -v

                        -------------

   Looking for a complete monitoring and management tool for PM2?
    _                             _        _            _
   | | _____ _   _ _ __ ___   ___| |_ _ __(_) ___ ___  (_) ___
   | |/ / _ \ | | | '_ ` _ \ / _ \ __| '__| |/ __/ __| | |/ _ \
   |   <  __/ |_| | | | | | |  __/ |_| |  | | (__\__ \_| | (_) |
   |_|\_\___|\__, |_| |_| |_|\___|\__|_|  |_|\___|___(_)_|\___/
             |___/

                          Features

                   - Real Time Dashboard
                   - CPU/Memory monitoring
                   - HTTP monitoring
                   - Event notification
                   - Custom value monitoring
                   - Real Time log display

                          Checkout

                   https://keymetrics.io/

                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
2.1.6
```
Maybe it's useful tips or trick or troubleshoot note for [tutorial page](http://pm2-meteor.betawerk.co/).

**Comment by andruschka** [comment]
Ah yep it normally nodejs's binary is "node" and not "nodejs" 👌
