### ISSUE TITLE
Deploy progress indicator(message) winking very fast

### ISSUE THREAD

**Issue by cyclops24** [andruschka/pm2-meteor#39]
Hi @andruschka ,
It's a small issue 😉 
Deploy progress indicator winking between two text value like below:
Building your app and deploying to host machine \
Sometimes:
[===========                                                 ] 40%
and again:
Building your app and deploying to host machine |
[============                                               ] 41%
Building your app and deploying to host machine /
[==============                                          ] 42%
Building your app and deploying to host machine \
[===============                                        ] 43%
Building your app and deploying to host machine |
[================                                     ] 44%
This is winking very fast and I can't see progress percentage sometimes.

**Comment by andruschka** [comment]
Oh ok yes I see :D but I actually use a 3rd party module so this is a bug there  I think ...
