### ISSUE TITLE
Rename command to more firendly

### ISSUE THREAD

**Issue by andrejsm** [andruschka/pm2-meteor#4]
Let's rename `pm2-meteor` to something like `pmm`

**Comment by andruschka** [comment]
Yes you are right - this started as a pm2-json generator and now bacame a bigger thing. We will search for a better name.

**Comment by andruschka** [comment]
I outsourced this task to crater.io. Let's see what the community thinks...

**Comment by dalerka** [comment]
If the primary purpose of this package is to help with deployment, perhaps `pm2go` or `pm2run` or `pm2host` or `pm2serve` may fit?

**Comment by andruschka** [comment]
I think the name will remain pm2-meteor for now
