### ISSUE TITLE
App didn't run automatically after host reboot antil pm2-meteor start from local

### ISSUE THREAD

**Issue by cyclops24** [andruschka/pm2-meteor#41]
Hi @andruschka ,
I deply one app with your tools and it seems all things now is OK. But when I reboot my server app didn't run automatically with pm2 on server boot.
I don't know why but after run `pm2-meteor start` from my local machine app started successfully.

What is the issue man? :thinking: 
Do you have any suggestion for troubleshoot this?

**Comment by andruschka** [comment]
Yes of course - good point although - you simply have to setup the pm2 service like [described here](http://pm2.keymetrics.io/docs/usage/startup/) and it will launch automatically ^^

**Comment by andruschka** [comment]
So if you are using ubuntu as server os and are logged in as your default app user just type `pm2 startup ubuntu` - that should be it

**Comment by cyclops24** [comment]
Ohhh thanks man. It's working good. 👏
