### ISSUE TITLE
set --mobile-server

### ISSUE THREAD

**Issue by philcruz** [andruschka/pm2-meteor#48]
I have my app deployed to the server and it works fine. The mobile app is not connecting to the server. I think I need to pass --mobile-server when meteor i started on the server. How would I do that with pm2-meteor?

**Comment by eleventy** [comment]
The --mobile-server flag sets the following env variables:
* MOBILE_DDP_URL
* MOBILE_ROOT_URL

So if you set those vars, you should be good to go.

You can add env's in pm2-meteor.json : 
```
{
 ...
  "env": {
    "ROOT_URL": "http://YOUR-URL",
    "PORT": 3000,
    "MOBILE_DDP_URL": "http:/YOUR-URL",
    "MOBILE_ROOT_URL": "http:/YOUR-URL",
    "MONGO_URL": "mongodb://localhost:27017/YOURDB"
  },
...
}
```

Not tested, but should work I think

**Comment by philcruz** [comment]
I have set the MOBILE_DDP_URL and MOBILE_ROOT_URL as you have shown. My app is still not connecting. This is hard to debug on a mobile device but in client code I am doing 
`console.log(Object.keys(__meteor_runtime_config__));`
I can see that output when I connect to my device by USB and do `adb logcat`. it shows
"meteorRelease,ROOT_URL,ROOT_URL_PATH_PREFIX,DDP_DEFAULT_CONNECTION_URL,autoupdateVersionCordova,appId,meteorEnv". 

When I console.log ROOT_URL and DDP_DEFAULT_CONNECTION_URL I get "http://mydomain.com:80" as I expect. When I console.log ROOT_URL_PATH_PREFIX I get "". 

Should I see values for MOBILE_DDP_URL and/or MOBILE_ROOT_URL? 

Here's what I'm seeing for the output
```
01-10 13:32:18.252  6770  6770 I chromium: [INFO:CONSOLE(254)] "STARTING MYAPP...", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.253  6770  6770 I chromium: [INFO:CONSOLE(254)] "meteor_runtime_config", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.254  6770  6770 I chromium: [INFO:CONSOLE(254)] "meteorRelease,ROOT_URL,ROOT_URL_PATH_PREFIX,DDP_DEFAULT_CONNECTION_URL,autoupdateVersionCordova,appId,meteorEnv", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.255  6770  6770 I chromium: [INFO:CONSOLE(254)] "http://mydomain.com:80/", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.255  6770  6770 I chromium: [INFO:CONSOLE(254)] "http://mydomain.com:80/", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.255  6770  6770 I chromium: [INFO:CONSOLE(254)] "", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
01-10 13:32:18.587  6770  6770 I chromium: [INFO:CONSOLE(254)] "routes.Meteor.startup...", source: http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js?meteor_js_resource=true (254)
```

Why is there "http://localhost:12488/55eb7342dbe69de9834025dba739db934786c3e8.js"? Shouldn't that be pointing to mydomain.com?

**Comment by philcruz** [comment]
When I go to the app in the browser, it comes up fine. If I view source I can see the code it uses on the server to set up the __meteor_runtime_config__. If I decode it I get


`__meteor_runtime_config__ = JSON.parse(decodeURIComponent("{"meteorRelease":"METEOR@1.4.2.3","meteorEnv":{"NODE_ENV":"production","TEST_METADATA":"{}"},"PUBLIC_SETTINGS":{},"ROOT_URL":"http://mydomain","ROOT_URL_PATH_PREFIX":"","appId":"8bc2k4wt8sqc1rfg2e0","autoupdateVersion":"5045103db38aa3ecc9db10e81d6f6388442ad78e","autoupdateVersionRefreshable":"cd868237a70cfff2cf6abff6d0abb4ae190b1304","autoupdateVersionCordova":"dcc2a237bab47e8dd4c54effddcb17e9c1b2fd66"}"))`

I don't see DDP_DEFAULT_CONNECTION_URL. Could that be the issue?

**Comment by eleventy** [comment]
Not really an expert on Cordova and Meteor, but did you specify your production domain whilst building for Cordova?

In fact, come to think of it, your Meteor server probably does not need to have the mobile-server.  It's your mobile app that needs to know when building, not the server.

In development try reinstalling your app with `meteor run android-device --mobile-server http://myserver.com`    It should no longer try to connect to your localhost.

In production, try [these settings](https://guide.meteor.com/mobile.html#building-for-production)

**Comment by philcruz** [comment]
Yes, in development doing 
`meteor run android-device --mobile-server http://myserver.com` works fine. As discussed in this (really long) thread https://github.com/meteor/meteor/issues/3698 people are having problems building for production. `meteor build somefolder --server http://myserver.com` just doesn't seem to work as it should. 

It talks about 2 workarounds https://www.screencast.com/t/eBu95umDrkb

I tried setting DDP_DEFAULT_CONNECTION_URL (in addition to MOBILE_DDP_URL and MOBILE_ROOT_URL) as an environment variable and that didn't work. So the only thing left to try is to run meteor on the server with --mobile-server.

**Comment by philcruz** [comment]
I was finally able to get my app to connect. Not exactly sure why but adding a minimal mobile-config.js seems to have resolved it. I thought that was entirely optional and I wasn't getting any errors without it but the app is connecting now. I'm guessing it has something to do with autoupdate and setting the App.info.id??

**Comment by erperejildo** [comment]
I've got the same issue and my mobile-config looks ok. What did you add @philcruz?
