### ISSUE TITLE
Question: HTTPS SETUP

### ISSUE THREAD

**Issue by boustanihani** [andruschka/pm2-meteor#5]
Could you please add info for setting up HTTPS to the readme?

**Comment by andruschka** [comment]
This is a #todo. Will add that in next version.

**Comment by miri-am** [comment]
Hi @andruschka. Is there a chance this will be added anytime soon?

**Comment by mwkrieger** [comment]
Hi @andruschka - any chance that the new version that you're releasing soon will have HTTPS support? I noticed that about 11 days ago you mentioned that a new version would be coming this week - so I'm crossing my fingers! :)

**Comment by daaaaan** [comment]
+1 :)

**Comment by aleritty** [comment]
+1 to https

**Comment by andruschka** [comment]
Done
