### ISSUE TITLE
the nvm options is unuseful.

### ISSUE THREAD

**Issue by boostbob** [andruschka/pm2-meteor#54]
i have custom the nvm options, just following:

```
"nvm": {
   "bin": "~/.nvm/nvm.sh",
   "use": "4.6.1"
},
```

i have deployed the web application，it works，but i type pm2 show [appname] to found that:

```
interpreter       │ node                                       │
│ interpreter args  │ N/A                                        │
│ script id         │ 4                                          │
│ exec cwd          │ /var/www/pmtools                           │
│ exec mode         │ cluster_mode                               │
│ node.js version   │ 6.2.0                                      │
│ watch & reload    │ ✘                                          │
│ unstable restarts │ 0                                          │
│ created at        │ 2017-02-23T01:47:33.932Z 
```

the node version is 6.2.0，not 4.6.1，is there some thing wrong with me?

**Comment by StephanGeorg** [comment]
No, nothing wrong. Seems not working.

**Comment by andruschka** [comment]
Hmm 🤔
Actually this should work... 
I will have a look.

**Comment by Rebolon** [comment]
Seems to work for me BUT, on the server i had to  : 

 * delete the app (pm2 delete My_APP_ID) and deploy again.

Even if i restart the app through pm2 restart the new node instance was not used that's why i decided to delete the app. 
If there is a better way i'm interested in :-)

**Comment by crapthings** [comment]
we have nvm on our server and its working.

**Comment by Rebolon** [comment]
i'm interesting on how you do this ? personaly i filled the file pm2-meteor.json with 

```
server: { 
  nvm: { 
    bin: 'fullPathTo/.nvm/nvm.sh', 
    use: '8.5.0' 
  }
}
```

i've also done an nvm install 8.5.0 on server
But when i deployed from my local machine, then the app still use the node 4.x

**Comment by crapthings** [comment]
```

"server": {
  
    "nvm": {
      "bin": "/home/cube/.nvm/nvm.sh",
      "use": "v4.7.3"
    }
  }
```


maybe  a missing of v ?

**Comment by Rebolon** [comment]
i will try but am not sure coz i don't use 'v' when i manually use nvm

**Comment by crapthings** [comment]
yes when using nvm
we normally use nvm use 4 nvm use 8 etc

**Comment by crapthings** [comment]
https://github.com/andruschka/pm2-meteor/blob/master/src/remoteTasks.coffee#L33

check this line

maybe it doesn't use that property to find which node to use

maybe we should force nvm alias default ?

we only have one node version, that's why it works. maybe

**Comment by Rebolon** [comment]
ok, you're right. Now that i only have one node version it works also. I d'ont understand why it's commented in fact

**Comment by crapthings** [comment]
@andruschka any news ?

~~~it seems its okay to uncomment that nvm.use to make it work~~~

**Comment by crapthings** [comment]
first attempt
https://github.com/andruschka/pm2-meteor/pull/71

**Comment by crapthings** [comment]
@andruschka i wonder will session keep connection to remote host ?
if it is disconnect we should nvm use version again

        remoteTasks.checkDeps session, pm2mConf, cb
        remoteTasks.reloadApp session, pm2mConf, reconfig, cb

i think its why nvm alias default works

```
  async.series [
      (cb)->
        remoteTasks.checkDeps session, pm2mConf, cb
      (cb)->
        remoteTasks.prepareHost session, pm2mConf, cb
      (cb)->
        localTasks.generatePM2EnvironmentSettings pm2mConf, cb
      (cb)->
        localTasks.bundleApplication pm2mConf, cb
      (cb)->
        remoteTasks.backupLastTar session, pm2mConf, cb
      (cb)->
        remoteTasks.shipTarBall session, pm2mConf, cb
      (cb)->
        remoteTasks.extractTarBall session, pm2mConf, cb
      (cb)->
        remoteTasks.installBundleDeps session, pm2mConf, cb
      (cb)->
        nvm use nvm.use again should
        remoteTasks.reloadApp session, pm2mConf, reconfig, cb
    ]
```

**Comment by crapthings** [comment]
@andruschka 

add nvm use different support 

https://github.com/andruschka/pm2-meteor/pull/72
