### ISSUE TITLE
Deploy app in 'fork-mode' for N instances in diferent ports

### ISSUE THREAD

**Issue by eportico** [andruschka/pm2-meteor#55]
Hi,
how can I deploy in fork-mode with N instances in diferent port to manage it with NGINX how sticky session load balancer ?
Actually, I can also specify only one port  in config and it crash the instantes because addr is in use.

thanks

**Comment by andruschka** [comment]
yes this is possible now!
Just set `server.freePorts = [3003, 3004 ... ]` whatever ports you want the fork_instances to use.
