### ISSUE TITLE
question: deploy only new settings.json

### ISSUE THREAD

**Issue by kamil7732** [andruschka/pm2-meteor#57]
Is there option to only deploy new settings.json? I don't need to build brand new bundle just send a changed settings.json file.

**Comment by eleventy** [comment]
For simple changes, I log into the server, modify the pm2-env.json file directly, and reload the app:

```
ssh my.server.com
...
cd /opt/pm2-meteor/myapp
nano pm2-env.json
...
pm2 reload myapp

```

**Comment by andruschka** [comment]
`pm2-meteor reconfig` will do it ;-)
