### ISSUE TITLE
Can't see my app running

### ISSUE THREAD

**Issue by erperejildo** [andruschka/pm2-meteor#60]
```
recipic@recipic:/etc/nginx/sites-enabled$ pm2 list
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ recipic  │ 0  │ cluster │ 25776 │ online │ 13025   │ 3s     │ 0%  │ 90.8 MB   │ disabled │
│ recipic  │ 1  │ cluster │ 25777 │ online │ 13025   │ 3s     │ 0%  │ 90.4 MB   │ disabled │
```
What do I need to do to see my app? If I go to `http://myIP` or `http://myIP:3000` I can't see anything.
This is also `myApp.conf` on `/etc/nginx/sites-enabled`:
```
server {
  listen 81;

  server_name http://myIP;

  # Tell Nginx and Passenger where your app's 'public' directory is
  root /home/recipic/apps/recipic/bundle;

  # Turn on Passenger
  passenger_enabled on;
  # Tell Passenger that your app is a Meteor app
  passenger_app_type node;
  passenger_startup_file main.js;

  # Tell your app where MongoDB is
  passenger_env_var MONGO_URL mongodb://localhost:27017/recipic;
  # Tell your app what its root URL is
  passenger_env_var ROOT_URL http://138.68.171.51;

  access_log /var/log/nginx/recipic.access.log;
  error_log /var/log/nginx/recipic.error.log;

 location / {
   proxy_pass http://127.0.0.1:3000;
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection 'upgrade';
   proxy_set_header X-Forwarded-For $remote_addr;
 }
}

```
I have no `default` file on same path

**Comment by andruschka** [comment]
hmm good question - i actually dont't know that.
I see that you are using passenger. Maybe it is because of that ? 
I tried passenger some years ago but could not bring it to work in a satisfying manner... 
What does pm2-meteor logs say?

**Comment by erperejildo** [comment]
I removed passenger from my server I also thought that could be related but it's not. I've got this .conf now:
```
server {
    listen 80;
    server_name _;
    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000;

        #configure websockets handling
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
I'm also commenting this issue here because I'm not sure what the problem is (at the end you'll see the logs):
https://forums.meteor.com/t/struggling-with-pm2-and-nginx/36224/13

**Comment by andruschka** [comment]
Our apps are configured like this:

```
server {
  listen 80;
  server_name your.app-domain.com;

  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://127.0.0.1:3000$request_uri;
  }
}
```

Maybe try that one.
And you did not specify your server_name (the root_url of your app)

**Comment by erperejildo** [comment]
I replaced the whole file but nothing changed. I put:
`server_name: http://138.68.171.51;`
I also restarted nginx.

Have you seen the logs on the link I posted? My app looks like if it restarting all the time but I don't have any of this issues on local.

**Comment by andruschka** [comment]
ok - i see
It looks like there is already an application bound to port 3000.
Maybe change to some free port?

**Comment by andruschka** [comment]
and for the bcrypt err try on your dev machine:
`rm -rf node_modules`
`npm r bcrypt --save`
`meteor npm i  bcrypt --save`
`meteor npm install`

**Comment by erperejildo** [comment]
I tried with other ports but I think that the port is not the problem. I got the same result.
I did that locally and looks ok, I don't get any message but when I deploy this version looks the same, no difference. I stopped it before with `pm2 kill`.
I'm running the same commands on my pipeline.

Should I try updating Meteor maybe?

**Comment by erperejildo** [comment]
I also changed my Node version on my server to 4.4.7, the one for Meteor 1.4.2.6 and I removed the cfs:gridfs package (found some related issues with it on internet).

Still the same

**Comment by andruschka** [comment]
ok could you please post the logs here then? I will try to help you

**Comment by erperejildo** [comment]
Nothing changed (just the reference to bcrypt) from the other posted but it changed locally (that's the weird thing):
- In blue:

```
PM2        | 2017-05-10 20:54:10: App name:recipic id:1 disconnected
PM2        | 2017-05-10 20:54:10: App [recipic] with id [1] and pid [1324], exited with code [0] via signal [SIGINT]
PM2        | 2017-05-10 20:54:10: Starting execution sequence in -cluster mode- for app name:recipic id:1
PM2        | 2017-05-10 20:54:10: App name:recipic id:1 online
```
- In green:

```
1|recipic  | { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
```
- In red:

```
1|recipic  | Error: bind EADDRINUSE 0.0.0.0:3000
1|recipic  |     at Object.exports._errnoException (util.js:873:11)
1|recipic  |     at exports._exceptionWithHostPort (util.js:896:20)
1|recipic  |     at cb (net.js:1315:16)
1|recipic  |     at rr (cluster.js:607:14)
1|recipic  |     at Worker.<anonymous> (cluster.js:577:9)
1|recipic  |     at process.<anonymous> (cluster.js:736:8)
1|recipic  |     at emitTwo (events.js:92:20)
1|recipic  |     at process.emit (events.js:172:7)
1|recipic  |     at handleMessage (internal/child_process.js:695:10)
1|recipic  |     at Pipe.channel.onread (internal/child_process.js:440:11)
1|recipic  | js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by erperejildo** [comment]
Other thing that I just tried was run `npm install` on my bundle/programas/server folder, clean the logs with `pm2 flush` and run `pm2 restart all`.
After that I run `pm2 log --lines 100` to check the logs out again but... same

**Comment by andruschka** [comment]
ah ok this looks weird:
```
Starting execution sequence in -cluster mode- for app name:recipic id:1
```

Where is this log coming from?

**Comment by erperejildo** [comment]
I understand that's defined on pm2-meteor.json:
```
"server": {
    "host": "138.68.171.51",
    "username": "recipic",
    "pem": "../private/recipic_mup_rsa",
    "deploymentDir": "/home/recipic/apps",
    "loadProfile": "",
    "exec_mode": "cluster_mode",
    "instances": 1
  }
```

**Comment by andruschka** [comment]
Ah ok you are using a newer version of pm2 :D it did not log that stuff back then.

**Comment by andruschka** [comment]
What does pm2 list say?

**Comment by andruschka** [comment]
`Error: bind EADDRINUSE 0.0.0.0:3000`
tells that the port 3000 is already in 🤔

**Comment by erperejildo** [comment]
pm2 list says the same but with less lines.

Should I use a different version then?

**Comment by erperejildo** [comment]
Hmmm, let me try changing it again

**Comment by andruschka** [comment]
Are you using several node versions ?

**Comment by erperejildo** [comment]
```
node -v && npm -v
v4.4.7
2.15.8
```

**Comment by andruschka** [comment]
could you do:
```
pm2 kill
ps aux | grep node
```

**Comment by erperejildo** [comment]
killed and
```
ps aux | grep node
recipic   6176  0.0  0.1  12944   928 pts/1    S+   21:12   0:00 grep --color=auto node
recipic  25246  0.0  0.2 891480  1328 ?        Sl   Apr20   0:00 node /usr/bin/pm2 kill
```

**Comment by andruschka** [comment]
ok and now:
netstat -na | grep 3000

**Comment by erperejildo** [comment]
```
netstat -na | grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN
```
I'm deploying with 3005. I tried with 3001 and I had the same problem maybe because I had something else running on that port as well

**Comment by andruschka** [comment]
yes ok so something is running on port 3000

**Comment by andruschka** [comment]
ah you know that if you are deploying with changes to then env you need to:
`pm2 deploy --reconfig`

**Comment by andruschka** [comment]
if you don't do --reconfig it wont change pm2-env.json

**Comment by erperejildo** [comment]
ok, changing the pipeline to pm2 deploy --reconfig then by default
Edit: I do pm2-meteor deploy. Should I run this on my server when I deploy then?
Edit 2: just checked on README that should be pm2-meteor reconfig

**Comment by andruschka** [comment]
no from your local machine

**Comment by andruschka** [comment]
yes pm2 reconfig will just deploy the new env settings

**Comment by erperejildo** [comment]
Now looks totally different (blue, green and red respectively):
```
PM2        | 2017-05-10 21:34:24: Stopping app:recipic id:2
PM2        | 2017-05-10 21:34:24: App name:recipic id:2 disconnected
PM2        | 2017-05-10 21:34:24: App [recipic] with id [2] and pid [7351], exited with code [0] via signal [SIGINT]
PM2        | 2017-05-10 21:34:24: pid=7351 msg=process killed
PM2        | 2017-05-10 21:34:24: Starting execution sequence in -cluster mode- for app name:recipic id:2
PM2        | 2017-05-10 21:34:24: App name:recipic id:2 online

/home/recipic/.pm2/logs/recipic-out-2.log last 100 lines:
2|recipic  | { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

/home/recipic/.pm2/logs/recipic-error-2.log last 100 lines:
2|recipic  | js-bson: Failed to load c++ bson extension, using pure JS version

```

**Comment by andruschka** [comment]
ok this looks better now. Is your app accesssible?

**Comment by erperejildo** [comment]
nope... http://138.68.171.51:3005/

I also changed my app.conf on nginx/sites-enabled with the new port
EDIT: Oh yes, it's, without port

**Comment by andruschka** [comment]
ok - is your app erroring? if you do `pm2 m` does it restart all the time?

**Comment by erperejildo** [comment]
Thank you soooo much mate. So the problem was these 2 things then:
- the port was being used
- I needed to changed my deploy command on my YAML by `pm2 deploy --reconfig`

It doesn't restart  ;)

**Comment by andruschka** [comment]
So it works now ? Happy that I could help

**Comment by erperejildo** [comment]
like a charm :)
http://138.68.171.51/
