### ISSUE TITLE
Cannot update changes on app

### ISSUE THREAD

**Issue by erperejildo** [andruschka/pm2-meteor#62]
My app works as expected but when I do some changes (I was trying html + css changes) this doesn't change after re-deploy.

I do the deploy with `pm2-meteor reconfig` on a CI (Gitlab).

If I'm not wrong with pm2 you need to run `pm2 start app.js --watch` to update these changes but I don't know how to manage this with pm2-meteor.

Any ideas?

**Comment by andruschka** [comment]
yes sir (i think i need a better readme)
`pm2-meteor reconfig` -> will not deploy file changes - only deploys env var changes!
`pm2-meteor deploy` -> will deploy file changes but not env var changes!
`pm2-meteor deploy --reconfig` -> will deploy file changes and env changes

**Comment by andruschka** [comment]
Why? :
I removed env deployment from simple `pm2-meteor deploy` bacause most of the time you do only file changes and not env var changes so. (But if you want to restart your app with new env vars you need a hard restart which will mean some down time.)
`pm2-meteor reconfig` is for for the case where you only want to change an env var (like your mongo url changed - but don't want to hit the whole recompile process)

**Comment by erperejildo** [comment]
ok, so if I do pm2-meteor deploy --reconfig I'm just updating everything. That's cool.
Thanks again!

**Comment by erperejildo** [comment]
updated this post as well: http://stackoverflow.com/questions/41980898/how-do-i-force-pm2-to-update-my-meteor-app-server-side-after-a-deployment/43915917#43915917

**Comment by andruschka** [comment]
yes that's right 💯
