### ISSUE TITLE
Cannot deploy with new version

### ISSUE THREAD

**Issue by erperejildo** [andruschka/pm2-meteor#67]
Since I updated to new version I need to run every command with `sudo`, otherwise I get this error:
```
recipic@vultr:~$ pm2 --version
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect EACCES /home/recipic/.pm2/interactor.sock
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
recipic@vultr:~$ sudo pm2 --version
2.6.1
```
This is not a problem on my server but it's on my pipeline on which I can't use `sudo`:
```
$ pm2-meteor deploy --reconfig
Building your app and deploying to host machine
/builds/erperejildo/food-app/.deploy/bundle.tar.gz
/home/recipic/apps/recipic/bundle.tar.gz
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect EACCES /home/recipic/.pm2/interactor.sock
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)


OK: Deployed your app on the host machine!
```

I'm not quite sure if the problem is related with pm2 or pm2-meteor but either way the deploy is not working

**Comment by eleventy** [comment]
Maybe check the user:group properties of your .pm2/ folder and files on the server, and also the server-user you defined in your local pm2-meteor config file.  They should be the same, and certainly not the root user.

**Comment by erperejildo** [comment]
I'm using the same ssh key that I use to connect by terminal to my server and the user is correct. Well, it was also working before. Should I give permissions to some folders?

**Comment by eleventy** [comment]
Well,  pm2 shouldn't be run as root-user.  You should be able to `pm2 --version` without sudo. 
Check the [pm2 docs](http://pm2.keymetrics.io/docs/usage/startup/) for startup configuration,  especially the part about
```bash
pm2 startup

[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/home/unitech/.nvm/versions/node/v4.3/bin pm2 startup <distribution> -u <user> --hp <home-path>
```
( And restart the server ) 

This makes pm2 run at startup as \<user\>.   As long as you have to sudo for pm2, pm2-meteor will have troubles

**Comment by erperejildo** [comment]
I'm a bit confused...
I get this error on my pipeline so that's not my server. I push to Gitlab and it manages the deploy to my server on which I have not any `unitech` folder on `home`.

If I need to add this to the pipeline we have the same issue: I can't run `sudo`

**Comment by eleventy** [comment]
Well, if I'm not misreading your first comment, you get an error on the server if you run `pm2 --version` and not if you run `sudo pm2 --version`.   So, it's a problem on the server, and that should be fixed first.  You should be able to run a pm2 command as non-root

**Comment by erperejildo** [comment]
Oh yes, what I meant with that is that the problem with pm2 is related with the new version and it's failing on both platforms/servers: on my pipeline on Gitlab and on my server (also on my normal OS).

I get the same error running different commands without `sudo` and maybe I can fix the issue on my server but that's not going to change the deployment on my pipeline.

I can run `sudo` as normally on my server and that's not a problem, just on the pipeline.

Maybe I need some configuration like the one you pasted before to add it to my `YAML` file. I checked out that path as well on the pipeline and is not there.

**Comment by erperejildo** [comment]
Ok, I fixed the problem on the server with this:
```
$ sudo chown userName:userName ~/.pm2/rpc.sock
$ sudo chown userName:userName ~/.pm2/pub.sock
```
And this automatically fixed the issue on the pipeline (I thought both platforms were unrelated).

Thanks!
