### ISSUE TITLE
Question: how do I run a startup script

### ISSUE THREAD

**Issue by frankwo1** [andruschka/pm2-meteor#69]
in my package.json I have 
    "start": "meteor node public/app.js"
where do I list my start script?

**Comment by crapthings** [comment]
hi @frankwo1 

if u're using ubuntu as server you can create a service file

```
sudo nano /etc/systemd/system/myapp.service
```

paste something like this, change your project folder.

```
[Unit]
Description=myapp
[Service]
Type=simple
User=USERNAME
WorkingDirectory=/myapp
ExecStart=/bin/bash -c "source env.sh; ./run.sh"
Restart=on-abort
[Install]
WantedBy=multi-user.target
```

try start ur service, it will failed if your config is wrong

```
systemctl start myapp.service
```

if its working, u can check its status.
```
systemctl status myapp.service
```

this will enable service on reboot
```
systemctl enable myapp.service
```

**Comment by frankwo1** [comment]
Thanks

**Comment by crapthings** [comment]
@frankwo1  pm2 has startup

pm2 startup

http://pm2.keymetrics.io/docs/usage/startup/
