### ISSUE TITLE
Instance ports

### ISSUE THREAD

**Issue by jonbaer** [andruschka/pm2-meteor#7]
I am currently already using pm2 and deploy 4 instances under their own ports for lb so will the instances declared used incremental ports or do you have to define them somehow?

**Comment by andruschka** [comment]
They will use inc ports :) (pm2 will pick some) since I just started this project, there is currently no option for selecting ports for instances sorry

**Comment by jonbaer** [comment]
That is what I meant if I specify 8080 to PORT on my main meteor app the instances will take 8080:8081:8082:8083 correct?

**Comment by jonbaer** [comment]
Just FYI, this is the pm2 example I am currently running (so I am trying to figure out the deploy) ... https://github.com/RocketChat/Rocket.Chat/blob/master/example-pm2.json

**Comment by andruschka** [comment]
Sorry for late response - had a tough week. We didn't use fork_mode thats why you just had to deploy multiple time with different ports... What do you think - what is the best solution for this one? Maybe somethink like "usePorts": [3001,3004,...]
Or just incrementing ports?

**Comment by aleritty** [comment]
+1 to specify ports in some way

**Comment by andruschka** [comment]
It only took 1 year for me 😂
`server.freePorts = [3003, 3004]`
