### ISSUE TITLE
Shout out to PM2

### ISSUE THREAD

**Issue by formspoint** [andruschka/pm2-meteor#75]
Just want to give a big shout out to this repo and everyone behind it.  I've been using Meteor for about 3 years now, and all the time I used MUP.  Until the other day, when I jumped to Meteor 1.6.1.  MUP is broke with Meteor 1.6.1.  After pulling my hair out, and rebuilding servers, for a day, I finally tried PM2.

This worked almost out of the box and was super easy to get started with.

Thank you PM2!

**Comment by andruschka** [comment]
Actually pm2 is a seperate project I am not involved into - but i loved it since ever so I started using it for meteor... Then I created pm2-meteor because I was sick of rebuilding meteor for deployment and shipping it to the servers ...

**Comment by andruschka** [comment]
But I am glad you like it.
