### ISSUE TITLE
Node, npm, pm2 'not installed' on Webfaction CentOS 7

### ISSUE THREAD

**Issue by FransTwisk** [andruschka/pm2-meteor#8]
I'm trying to deploy on a shared hosting account on Webfaction servers, but it keeps on returning: "Please make sure you have node, npm and pm2 installed on your remote machine!". If I manually check if node, npm and pm2 are accessible via ssh, they are... Any way to better debug this?

Only thing I see happening is a .pm2 folder. The logfile in there reads:

```
2015-11-03 22:16:09: [PM2][WORKER] Started with refreshing interval: 30000
2015-11-03 22:16:10: [[[[ PM2/God daemon launched ]]]]
2015-11-03 22:16:10: BUS system [READY] on port /home/scissor/.pm2/pub.sock
2015-11-03 22:16:10: RPC interface [READY] on port /home/scissor/.pm2/rpc.sock
```

**Comment by andruschka** [comment]
Hmm ok - I will check that  👍

**Comment by andruschka** [comment]
There will be coming a new version this week - which will cover some bugs and some new functions

**Comment by FransTwisk** [comment]
Thanks, looking forward. I actually might just switch my dev environment to Digital Ocean for more control :)

**Comment by andruschka** [comment]
Yes - that is what we did. You maybe have to handle more stuff - but you also have more liberties! And DO is really cheap...

**Comment by andruschka** [comment]
should be working with version 0.3.0 :smile:
